### PR TITLE
gunjanimage

### PR DESCRIPTION
**Pull request by gd2811**
line no. 58 Gunjan Kawale

### CODE REVIEW

**Comment by gdscghrcem** [comment]
gunjan, you have just uploaded your image please make changes in the index.html file and send the request again

**Comment by gd2811** [comment]
line no.58 Gunjan Kawale

**Comment by gd2811** [comment]
check now it is correct or not.

**Comment by gdscghrcem** [comment]
add your image file in line no. 58 you are just uploading image

**Pull request closed without merging**
